#!/bin/bash
DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0
display_result() {
dialog --title "$Title" \             # New appropriate Varibale       
--no-collapse \
--msgbox "$result" 0 0
}
while true; do
exec 3>&1
selection=$(dialog \
--backtitle "System Information" \    # create a dialog box that will be presented to the user
--title "Current directory: $PWD" \   # containing optional tasks that the utility can perform tasks  
--clear \                             # with the addtion of PWD to show the current directory.
--cancel-label "Exit" \
--menu "Please select:" $HEIGHT $WIDTH 4 \
"1" "Display System Information" \
"2" "Display Disk Space" \
"3" "Display Home Space Utilization" \
"4" "Select Directory" \
2>&1 1>&3)
exit_status=$Exit
exec 3>&-
case $exit_status in
$DIALOG_CANCEL)
clear
echo "Program terminated."          #if nothing from the utility is selected quit the program.
exit
;;
$DIALOG_ESC)
clear
echo "Program aborted." >&2
exit 1
;;
esac
case $selection in
0 )
clear
echo "Program terminated."
;;
1 )
result=$(echo "Hostname: $HOSTNAME"; uptime) # if "Display System Information" is entered then provide 
display_result "System Information"          # the user with the name of the system
;;
2 )
result=$(df -h)                              # display the file systems disk space usage that is readable
display_result "Disk Space"
;;
3 )
if [[ $(id -u) -eq 0 ]]; then
result=$(du -sh /home/* 2> /dev/null)
display_result "Home Space Utilization (All Users)"
else                                               # if the "Display Home space utilzation" is selected then provide  
result=$(du -sh $HOME 2> /dev/null)                # the user with an estimated file space in the home             
result=$(du -sh $HOME 2> /dev/null)                # directory.
display_result "Home Space Utilization ($USER)"
fi
;;
4) 
DIALOG=${DIALOG=dialog}

FILE=`$DIALOG --stdout --title "Please choose a file" --fselect $HOME/ 14 48`

case $Directory_Seletion in                        # provide a menu that the user can select between directories 
	0)                                               # and file names and store diretory in the varible "File".
		echo "\"$FILE\" chosen"
                cd $FILE ;;
	1)
		echo "Cancel pressed.";;
	255)
		echo "Box closed.";;
esac
;;
esac
done
